name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 81a5c102dd5ced60583b4fc153b678a5b05cb022ffce93f26f250e16a185bcda06-ae4ef1e6-070c-4387-857f-f87f7a87dbd400f29190da558e0f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src"
          output_location: "/src"
          skip_app_build: true
          app_artifact_location: "/src"
          skip_deploy_on_missing_secrets: true
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_STONE_0DA558E0F }} 